networks:
  pocket:
    driver: 'bridge'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'db'
    environment:
      - 'POSTGRES_DB=pocket'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    restart: 'on-failure'
    networks:
      - 'pocket'
  backend:
    image: 'ghkd110/jib_test:0.8'
    container_name: 'backend'
    environment:
      USE_PROFILE: prod
      NORM_PROP: docker1
      DIRECT_MSG: hello
    ports:
      - '8080:8080'
    restart: 'always'