networks:
  pocket:
    driver: 'bridge'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'db'
    environment:
      - 'POSTGRES_DB=pocket'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    restart: 'on-failure'
    networks:
      - 'pocket'