name: Database Setup

services:
  postgres:
    image: 'postgres:latest'
    env:
      POSTGRES_DB: pocket
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5
